-- MySQL Script generated by MySQL Workbench
-- Sun Nov 29 16:38:32 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mbtidb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mbtidb` ;

-- -----------------------------------------------------
-- Schema mbtidb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mbtidb` DEFAULT CHARACTER SET utf8 ;
USE `mbtidb` ;

-- -----------------------------------------------------
-- Table `mbtidb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mbtidb`.`users` ;

CREATE TABLE IF NOT EXISTS `mbtidb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`, `email`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mbtidb`.`mbti_results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mbtidb`.`mbti_results` ;

CREATE TABLE IF NOT EXISTS `mbtidb`.`mbti_results` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `mbti` VARCHAR(8) NOT NULL,
  `created_at` DATE NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `responses_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mbtidb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mbtidb`.`questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mbtidb`.`questions` ;

CREATE TABLE IF NOT EXISTS `mbtidb`.`questions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(255) NOT NULL,
  `direction` INT NOT NULL,
  `dimension` VARCHAR(8) NOT NULL,
  `meaning` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mbtidb`.`responses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mbtidb`.`responses` ;

CREATE TABLE IF NOT EXISTS `mbtidb`.`responses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mbti_result_id` INT NOT NULL,
  `question_id` INT NOT NULL,
  `response` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `response_mbti_result_id`
    FOREIGN KEY (`mbti_result_id`)
    REFERENCES `mbtidb`.`mbti_results` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `response_questions_id`
    FOREIGN KEY (`question_id`)
    REFERENCES `mbtidb`.`questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


CREATE USER 'mbtiApi' IDENTIFIED BY 'localsecret';

GRANT SELECT, INSERT, UPDATE ON TABLE mbtidb.* TO 'mbtiApi';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
